defaults:
  one: !REQUIRED
  two: two
  three: three
  cache_classes: true
  tree1:
    tree2: hey
    tree3:
      tree4: blah
  array_of_hashes:
    - key1: value1a
      key2: value2a
    - key1: value1b
      key2: value2b
  array_of_strings:
    - one
    - two
    - three
  key_allcaps_values_array_hash:
    ALLCAPS:
      - arr0: true
        arr1: one

defaults[test,cucumber,development]:
  cache_classes: false

defaults[test,cucumber]:
  one: one
